# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit
exclude: "^doc"
repos:
  ##################
  # Standard hooks #
  ##################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
      - id: trailing-whitespace

  ################
  # React hooks #
  ################
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.46.0" # Use the sha / tag you want to point at
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$

  ###################################
  # Spellcheck in comments and docs #
  ###################################
  # skipping of *.svg files is not working...
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.2.1
  #   hooks:
  #     - id: codespell
  #       args: ['--write-changes']
  #       exclude: CHANGELOG\.rst|\.(svg|pyc|drawio|dcf|eds)$
